spring:
  application:
    name: rag
  servlet:
    multipart:
      # 单个文件最大大小
      max-file-size: 50MB
      # 请求总大小限制
      max-request-size: 50MB
  ai:
    dashscope:
      api-key: ${LLM_API_KEY}
      embedding:
        options:
          model: text-embedding-v4
          dimensions: 768
    vectorstore:
      pgvector:
        # 向量索引类型
        index-type: HNSW
        # 距离度量，余弦值
        distance-type: COSINE_DISTANCE
        # 向量维度
        dimensions: 768
        # 批量处理大小
        max-document-batch-size: 9
        # 启动时是否自动创建表
        initialize-schema: true
        # 创建的表名
        table-name: vector_st
  datasource:
    url: jdbc:postgresql://localhost:5433/rag
    username: pgvector
    password: 123456
